### PR TITLE
Fix for the ir-filter switch

### LINKED ISSUE #36: Night mode not working properly
At night, there's essentially no IR, all i see is black.  I've tried toggling the auto night mode/IR sensors on and off to no effect.  Also, the 4 IR lights are on all the time, not sure that's related or not.

### PR DESCRIPTION
**Pull request by PH89**
Makes IR-Filter feature working again by setting the GPIO 25 to oporate in output mode.

No more darkness! 💡 🎉 

This fixes #36

### CODE REVIEW

**Comment by phantomdarkness** [comment]
Tried this, mine still is pretty dark

**Comment by PH89** [comment]
Did you hear a little click noise after switching the ir-cut button?

Did you try these settings:

- IR-LED on ( keep in mind that the button has twisted state see #43, make sure IR-LED is shining.)
- IR-Cut off
- Rspt Night-Mode on ( Image should be BW, not colorful.)



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by phantomdarkness** [comment]
I don't believe I heard a click like I do with the original firmware no.  But I did implement #43 and tried turning the LED lights on, IR-Cut to off and RSPT to night mode.

**Comment by PH89** [comment]
No click means that the IR-filter is still active, what is the reason you can't see good in the dark. 
After adding the line did you do a restart? (sorry for that classical question, but its the only thing I have in mind why its not working.)

**Comment by phantomdarkness** [comment]
I did do a restart (and don't worry about the classical questions, sometimes people miss the obvious).  I'll try again tonight when it's dark and see if I have any luck.

**Comment by PH89** [comment]
If it is not working, can you try run:
`echo 1 > "/sys/class/gpio/gpio25/value"`
`echo 0 > "/sys/class/gpio/gpio26/value"`

These calls are made when you turn off the IR-filter. 
Is there an error message after calling?

**Comment by phantomdarkness** [comment]
Reflashed it and it seems to work.  Not automated though, I have to turn the things on/off in order for it to work properly but that's progress!

**Comment by PH89** [comment]
Yes automation isn’t working yet, the is a problem with the detection method:

https://github.com/openipcamera/openipc-firmware/blob/37e84143d3ee61072b02b0d4b9b736d0a52d0c94/firmware_mod/v2/scripts/ldr.sh#L14

Always writes 40, no matter how bright or dark the environment is. I guess the firmware of Wyze anf Xiaomi are working differntly in this point.

**Comment by PH89** [comment]
@SamHead Good catch!  I am curios if it will work after adding an LDR sensor. 

However the automatically switching is working in the stock firmware. This means camera is detecting the darkness over the CMOS-Sensor, with a software algorithm.

**Comment by openipcamera** [comment]
this is in the latest build as echo "out" > /sys/class/gpio/gpio25/direction
should achieve the same results.

**Comment by FuzzyMistborn** [comment]
@openipcamera It does not.  The IR lights are constantly on and nightvision does not work like it did when I used @PH89 's code.

**Comment by FuzzyMistborn** [comment]
Little more playing around, I have to disable the Auto Night mode in order to keep the IR lights off.  And the IR light switch is backwards for me.  On means the lights are off, Off means the lights are on.

**Comment by PH89** [comment]
This was fixed in #47.

**Comment by FuzzyMistborn** [comment]
Hrmmmm, right, wondering if I got a bad flash somehow?  Because it was working before when I made those changes myself but now when i updated to .26 it's not.  I'll try a reflash again and see if that fixes it.

**Comment by openipcamera** [comment]
fixed. 0.2.6 is missing that merge will fix shortly.

**Comment by openipcamera** [comment]
done

**Comment by TimelessNL** [comment]
> It seems that V2 does not have a LDR light sensor
> 
> See Q2 on https://www.wyzecam.com/forums/topic/wyze-cam-autopsy/
> 
> " It looks like the v2 no longer have a light sensor (Q2) which may be one of the reasons that mode switching behavior is different. "

Seems more camera manufactures are leaving the LDR out as [this](https://aliexpress.com/item/33020810043.html) camera does not have the LDR either. I'm currently looking for alternatives and one thing that caught my attentions is using [sunwait](https://github.com/risacher/sunwait) with cron in order to call the Majestic API endpoint to switch Day/Night. Luckily [sunwait is in buildroot](https://github.com/buildroot/buildroot/blob/master/package/sunwait/sunwait.mk) which to my understanding OpenIPC is based on.  Would it be possible to add sunwait to the lite image so camera's without LDR can have an alternative way of switching Day/Night mode?

**Pull request closed without merging**
